# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "prettydoc: Creating Pretty Documents From R Markdown"
email: yixuan.qiu@cos.name
description: Creating Pretty Documents From R Markdown

# Build settings
markdown: kramdown
highlighter: rouge

